### ISSUE TITLE
Not working with Ghostery Ad-Blocker.

### ISSUE THREAD

**Issue by tonystark93** [subramaniashiva/ad-block-test#1]
<img width="1438" alt="screen shot 2016-05-17 at 5 06 14 pm" src="https://cloud.githubusercontent.com/assets/11315443/15321163/62313b76-1c52-11e6-8995-afdf49ba1d01.png">
Hi. I am using ghostery adblocker. (https://www.ghostery.com/try-us/download-browser-extension). When i went to the page it says that "_You don't have ad-block_".

**Comment by subramaniashiva** [comment]
Hi Ashok, Thanks for using it. As I said in the description, this detects only ad-blockers. Ghostery is not a pure ad-blocker. it blocks all the sites that tracks you. So it might need a custom logic.

**Comment by tonystark93** [comment]
Hi shiva,
       Sorry, I thought Ghostery is an adblocker because it blocks the ad in webpages. Thanks for pointing out that Ghostery is the one that prevent the sites from tracking us.

**Comment by subramaniashiva** [comment]
Welcome :) Feel free to update this code if you find a way to detect blockers like ghostery.
